node 
{
    def app

    stage('Clone repository') 
    {
      

        checkout scm
    }

    stage('Update GIT') 
    {
        script 
        {
            catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') 
            {
                withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) 
                {
                    //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                    sh "git config user.email zefirnikolov@gmail.com"
                    sh "git config user.name ZefirNikolov"
                    //sh "git switch master"
                    sh "cat generator.yaml"
                    sh "sed -i 's+zefirnikolov/gen.*+zefirnikolov/test:${DOCKERTAG}+g' generator.yaml"
                    sh "cat generator.yaml"
                    sh "git add ."
                    sh "git commit -m 'Done by Jenkins Job: ${env.BUILD_NUMBER}'"
                    sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/k8scluster.git HEAD:main"
                }
            }
        }
    }
}
