apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/zefirnikolov/k8scluster.git
    targetRevision: HEAD
    path: ./
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
